In [4]:
import numpy as np
from sklearn.model_selection import train_test_split


In [5]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y=np.array([0,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1])


In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [10]:
x_train

array([ 1, 17, 11,  7,  6, 12, 13,  5, 14, 18,  4,  2,  9, 15, 16, 19])

In [11]:
len(x_train)

16

In [12]:
x_test

array([20,  8, 10,  3])

In [14]:
len(x_test)

4

In [15]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [16]:
len(y_train)

16

In [17]:
y_test

array([1, 0, 0, 1])

In [18]:
len(y_test)


4